### PR TITLE
Updated nginx Versions

### PR DESCRIPTION
**Pull request by lefte**
* Added nginx version 1.27
* Updated other bitnami versions
* Minor improvements to curl commands

### Bare minimum self-checks

> [What do you think of a person who only does the bare minimum?](https://getyarn.io/yarn-clip/dcf80710-425e-478b-bde1-c107bd11e849)

- [X] I've updated this PR with the latest code from `main`
- [X] I've done a cursory QA pass of my code locally
- [X] I've ensured all automated status check and tests pass
- [ ] I've [connected this PR to an issue](https://help.zenhub.com/support/solutions/articles/43000010350-connecting-pull-requests-to-github-issues)

### Pieces of flare

- [X] I've written a unit or functional test for my code
- [X] I've updated relevant documentation it my code changes it
- [X] I've updated this repo's README if my code changes it
- [X] I've updated this repo's CHANGELOG with my change unless its a trivial change (like updating a typo in the docs)

### Finally

- [X] I've [requested a review](https://help.github.com/en/articles/requesting-a-pull-request-review) with relevant people

If you have any issues or need help please join the `#contributors` channel in the [Lando slack](https://www.launchpass.com/devwithlando) and someone will gladly help you out!

You can also check out the [coder guide](https://docs.lando.dev/contrib/coder.html).

### CODE REVIEW

**Comment by lefte** [comment]
@reynoldsalec how do I add you as a reviewer? I feel like I might not have permissions to add you.

**Comment by reynoldsalec** [comment]
Probably missing write permissions, I added you to the repo @lefte.

These failing tests are weird...they're supposed to fail (there is no https), but for some reason the error processing isn't working correctly. Definitely not related to anything you did AFAIK.

**Comment by AaronFeledy** [comment]
It's failing at `lando ssh -s defaults -c "curl https://localhost" || echo $? | grep 1` on all the tests because curl, as expected, returns error code 7 but the test is checking for error code 1. This worked in the past due to a bug in Lando that was swallowing exit codes instead of passing them along. That was fixed in the latest Lando release. The tests will need to be updated to check for exit code 7.

**Comment by lefte** [comment]
> It's failing at `lando ssh -s defaults -c "curl https://localhost" || echo $? | grep 1` on all the tests because curl, as expected, returns error code 7 but the test is checking for error code 1. This worked in the past due to a bug in Lando that was swallowing exit codes instead of passing them along. That was fixed in the latest Lando release. The tests will need to be updated to check for exit code 7.

Makes sense, that was my thought as well, I'll make some changes to expect the right message result.

**Comment by lefte** [comment]
Okay, I think I might have updated the 1.27 README to work in Leia, someone will have to trigger the test to run again, I don't have permission for that.

**Comment by reynoldsalec** [comment]
Looks great thanks @lefte for fighting the good fight here!

**Pull request merged**
